/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kafkaworkshop;
@org.apache.avro.specific.AvroGenerated
public enum Color implements org.apache.avro.generic.GenericEnumSymbol<Color> {
  RED, YELLOW, GREEN, BLUE, PINK, PURPLE, MAGENTA  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Color\",\"namespace\":\"kafkaworkshop\",\"symbols\":[\"RED\",\"YELLOW\",\"GREEN\",\"BLUE\",\"PINK\",\"PURPLE\",\"MAGENTA\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
