---
version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:5.5.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
#    volumes:
#      - ./schema:/opt/app/schema/


  nginx:
    image: nginx
    restart: "no"
    #restart: always
    #restart: on-failure
    #restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - kafkahq
    volumes:
      - ./:/src
    command: ./src/nginx/run_nginx.sh
    environment:
      - DOMAIN

  schema-registry-ui:
    image: landoop/schema-registry-ui:latest
    ports:
      - 25001:8001
    environment:
      SCHEMAREGISTRY_URL: http://localhost:8081
      ALLOW_GLOBAL: 'true'
      ALLOW_TRANSITIVE: 'true'
      ALLOW_DELETION: 'true'
      PORT: 8001
      PROXY: 'true'
    depends_on:
      - schema-registry

  kafkahq:
    image: tchiotludo/kafkahq
    hostname: kafkahq
    environment:
      KAFKAHQ_CONFIGURATION: |
        kafkahq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "broker:29092"
              schema-registry:
                url: "http://schema-registry:8081"
    ports:
      - 25000:8080
    depends_on:
      - broker
      - schema-registry
    links:
      - broker
      - schema-registry
